language: r
env: R_REMOTES_NO_ERRORS_FROM_WARNINGS=true
warnings_are_errors: true
cache: packages

r_packages:
  - covr
  - pkgdown

r_binary_packages:
  - magick

r_github_packages:
  - EricMarcon/dbmss
  - EricMarcon/entropart
  - EricMarcon/SpatDiv

after_success:
  - Rscript -e 'library(covr); codecov(type ="all")'
  - mkdir docs
  - git fetch origin gh-pages:gh-pages                 # Comment out for release
  - git --work-tree=docs checkout gh-pages -- .        # Comment out for release
  - travis_wait 60 Rscript -e 'pkgdown::build_site()'
  - touch docs/.nojekyll

deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true                                   # Comment out for release
  token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: docs

notifications:
  email:
    recipients:
      - e.marcon@free.fr
