language: r
cache: packages

r_packages:
 - devtools
 - covr

r_github_packages:
 - EricMarcon/entropart
 - EricMarcon/SpatDiv

r_binary_packages:
    - magick

addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:opencpu/imagemagick'
      - sourceline: 'ppa:ubuntugis/ppa'
    packages:
      - libmagick++-dev
      - librsvg2-dev
      - libwebp-dev
      - libpoppler-cpp-dev
      - libtesseract-dev
      - libleptonica-dev
      - tesseract-ocr-eng
      - r-cran-rgdal
      - libfftw3-dev
      - cargo

after_success:
  - Rscript -e 'library(covr); codecov(type ="all")'
  - mkdir docs
#  - git fetch origin gh-pages:gh-pages                 # Comment out for release
#  - git --work-tree=docs checkout gh-pages -- .        # Comment out for release
  - travis_wait 60 Rscript -e 'pkgdown::build_site()'
  - touch docs/.nojekyll

deploy:
  provider: pages
  skip_cleanup: true
#  keep_history: true                                   # Comment out for release
  token: $GITHUB_TOKEN
  on:
    branch: master
    local_dir: docs

notifications:
  email:
    recipients:
      - e.marcon@free.fr
