language: R
sudo: false
cache: packages

r_packages:
 - devtools
 - covr

r_github_packages:
 - EricMarcon/entropart
 - EricMarcon/SpatDiv

r_binary_packages:
    - libgit2
    - magick

after_success:
  - Rscript -e 'library(covr); codecov(type ="all")'
